title: Göçmenin Notları
author:
  name: Hasan Berkay Çağır
  email: berkay@cagir.com.tr
  twitter: berkaycagir
  url: https://cagir.me
description: Aklıma takılanları yazdığım blogum.
show_excerpts: true
url: https://blog.cagir.me
twitter:
  username: berkaycagir
  card: summary
social:
  links:
    - https://twitter.com/berkaycagir
    - https://github.com/berkaycagir
    - https://www.linkedin.com/in/berkaycagir
locale: tr_TR
google_site_verification: 1OuSczG16tDyhfKy90bpQJaL8rpkTqhObUktPSlJjmY
repository: berkaycagir/berkaycagir.github.io
lang: tr
paginate: 10
paginate_path: /page:num/
# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%d/%-m/%Y"
  skin: dark
  # generate social links in footer
  social_links:
    twitter: berkaycagir
    github:  berkaycagir
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    linkedin: berkaycagir
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    keybase: berkay

    # Mastodon instances
    mastodon:
    - username: berkay
      instance: mastodon.com.tr
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    gitlab:
    - username: berkay
      instance: gitlab.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - hakkimda.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap
 - jekyll-gist
 - jekyll-github-metadata
 - jekyll-paginate
